kind: Service
apiVersion: v1
metadata:
  name: cab-booking-postgres
  labels:
    name: cab-booking-postgres
spec:
  ports:
    #- nodePort: 30163
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: cab-booking-postgres
  #type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cab-booking-postgres
spec:
  selector:
    matchLabels:
      app: cab-booking-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: cab-booking-postgres
    spec:
      containers:
        - name: cab-booking-postgres
          image: chanduyerramsetti/cab-booking-postgres
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password